# Generated by Django 4.0.4 on 2022-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('departure', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('altitude_dep', models.IntegerField(default=0)),
                ('altitude_min', models.IntegerField(default=0)),
                ('altitude_max', models.IntegerField(default=0)),
                ('height_dif_pos', models.IntegerField(default=0)),
                ('height_dif_neg', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
    ]
